name: clean_arc
description: It is a tool to create clean architecture modules structure folders.
version: 1.0.2
homepage: https://github.com/ArielFarias/clean-arc

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  args: ^2.7.0
  pub_api_client: ^3.1.1
  

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2
  
executables:
  clean_arc:
