name: clean_arc
description: It is a tool to create clean architecture modules structure folders.
version: 1.0.0
homepage: https://github.com/ArielFarias/clean-arc

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  args: ^2.3.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

executables:
  clean_arc:
